name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
            echo "helloworld"
            echo "Balamuc is something"
            echo "HopenShit"
      - name: print goodby
        run: echo "goodbye"
        
      
